stages:
  - test
  - build

image: ubuntu:18.04

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Caching pip and apt packages
cache:
  paths:
    - .cache/pip
    - venv/
    - apt-cache/

before_script:
  - apt update
  - apt-get -o dir::cache::archives="apt-cache" install -y wget gnupg2 software-properties-common python3.6 python3-pip git language-pack-pl
  # Install Morfeusz Ubuntu package
  - wget -qO - http://download.sgjp.pl/apt/sgjp.gpg.key | apt-key add -
  - apt-add-repository http://download.sgjp.pl/apt/ubuntu
  - apt update
  - apt-get -o dir::cache::archives="apt-cache" install -y morfeusz2
  - python3 -V
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test_job:
  stage: test
  script:
    - pytest

build_job:
  stage: build
  script:
    - python3 make_dictionary.py stats make
  artifacts:
    paths:
      - ./*.mobi
      - ./dictionary_stats_*.json
    expire_in: never
  timeout: 15m
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
